### ISSUE TITLE
let g:C_Ctrl_J = 'off' ignored | c.vim

### ISSUE THREAD

**Issue by osleg** [WolfgangMehner/vim-plugins#21]
Hello, 
I'm using <C-J> for buffers navigation. Was looking for a way to re-map c.vim's <C-J> functionality but it seems that it can be only turned off.
Though, setting let g:C_Ctrl_j = 'off' in my .vimrc does nothing. 
I can see it as "off" from vim, also the placeholders are not working but the keybindin is still acting like c.vim's one (jumps after the '}' or ')' etc)

**Comment by WolfgangMehner** [comment]
Just for clarification:
In the title you wrote g:C_Ctrl_J and in the post g:C_Ctrl_j .
Which one is actually your vimrc? Lowercase "j" is correct.

**Comment by osleg** [comment]
It was uppercase, changed to lower case, works now, sorry and thanks! :)

**Comment by WolfgangMehner** [comment]
No problem.
