### ISSUE TITLE
Kep mapping conflict between c-support and vcscommand: Mapping already in use: "<LocalLeader>cd", mode "n"

### ISSUE THREAD

**Issue by monkeyqyf** [WolfgangMehner/vim-plugins#24]
C.vim and vcscommand.vim are all quite popular plugin and frequently downloaded from vim.org. 
C.vim is for c support and vcscommand is for version control system support, both are highly possible to work together. 
While there's a kep mapping conflict as the title when opening a c source file. I also get the output of :verbose map \<localleader\>cd

v  \cd         *@<Esc>:call mmtemplates#core#InsertTemplate(g:C_Templates,"Comments.date")<CR>
        Last set from /media/sf_env_share_folder/home/.vim.yann/autoload/mmtemplates/core.vim
n  \cd           <Plug>VCSDiff
        Last set from /media/sf_env_share_folder/home/.vim.yann/plugin/vcscommand.vim

Currently, is there any method to mask the \cd from c.vim? Or will this mapping be changed later on?

**Comment by WolfgangMehner** [comment]
You can change this key in the template library. See the menu entry Snippets -> edit local templates. Yp

**Comment by WolfgangMehner** [comment]
To be more specific:
- The maps which are generated from the template library never overwrite existing mappings. Neither global ones nor those from the filetype plug-ins.
- Most templates define a map in their header, using the map:... option. The template which is causing the conflict is Comments.date . You can remove the map by removing the option completely, or change it by giving another map, such as map:cda .

**Comment by monkeyqyf** [comment]
Thanks for your response.

**Comment by coldspark29** [comment]
Well, for me the plugin either complains, that the personal details are not set or these error messages appear:

```
Mapping already in use: "<LocalLeader>cd", mode "n", command:
  <Plug>VCSDiff
Mapping already in use: "<LocalLeader>is", mode "n", command:
  :IHS<CR>:A<CR>
Mapping already in use: "<LocalLeader>is", mode "i", command:
  <Esc>:IHS<CR>:A<CR>
```

**Comment by WolfgangMehner** [comment]
Sorry for the long wait.

> Even if I uninstall all other plugins, the error messages don't disappear.

You can use `:scriptnames` on the Vim command-line to see what was loaded.

> I don't even have a map in my templates file.

Templates get loaded from several locations. Go to a buffer with the correct filetype (the filetype for which you have the templates), and use the map `\rs`. It will show you information about the plug-in and all the template files it loads.

**Comment by coldspark29** [comment]
No problem. I have disabled the plugin some time ago. I just installed it again and the problem seems to be gone. Maybe there were really some files missing.
