### ISSUE TITLE
The idiomatic way to add more templates to new file

### ISSUE THREAD

**Issue by antonvesnin** [WolfgangMehner/vim-plugins#28]
It's more a question, not an issue.
Let's say i want add header quards autmoatically to every new .h file. I added new template to c.preprocessor.template, but i failed to figure out how to make it add to every new file, like it does with comment.file-description-header from c.comments.template.

Of coures I can just add it to file-description-header template, but it just looks wrong. What is the right way? Or point me to the documentation describing this case. Thanks.

**Comment by WolfgangMehner** [comment]
The insertion of "Comment.file-description-header" is hardwired until now. I can see how this is problematic. Let me come back to this later today or this week.

**Comment by WolfgangMehner** [comment]
As a quick fix, you could add this to your .vimrc:
```
  g:C_InsertFileHeader = 'no'
```
Now no file headers will be inserted automatically. So you can always choose the right one from the template library.

I will address the more general issue later

**Comment by antonvesnin** [comment]
Thanks, that's good, but it's more likely opposit what i asked, i asked a way to specify which templates will be included automatically, to add one after comment header. But i hope you will address it later, like more general issue.

**Comment by WolfgangMehner** [comment]
This has been addressed (for C-Support) by 3c9d87b7c37e4 .

For the documentation, see here:
https://github.com/WolfgangMehner/vim-plugins/blob/3c9d87b7c37e4bab2eede268aea2c6961e8965b8/doc/csupport.txt#L1853

This functionality will be added to the other plug-ins as well, stay tuned ...

**Comment by WolfgangMehner** [comment]
I've added this to a couple of other plug-ins:
[News - Customizable File Skeletons](http://wolfgangmehner.github.io/vim-plugins/news.html#NEWS_SKELETONS_JUL2017)

And also to Latex-Support:
https://github.com/WolfgangMehner/vim-plugins/commit/97a3a9f0895259ef6b7dbac77b9674c517ddf01d
