### ISSUE TITLE
c-support undefined function

### ISSUE THREAD

**Issue by snakeleon** [WolfgangMehner/vim-plugins#29]
c-support plug-in undefined function (e.g. mmtemplates#wizard#setupwizard)
In c-support/makedist.sh file to add to package file list:
./autoload/mmtemplates/config.vim
./autoload/mmtemplates/wizard.vim

Please forgive my poor English. I hope that you can understand what i mean

**Comment by WolfgangMehner** [comment]
I've actually now switched to a new release script. Run

    lua project/release.lua c list

It should work with every version of Lua (5.1-5.3) which is around these days.
Or you can obtain the list directly from the source, look for:

    ------------------------------------------------------------------------
    --  C/C++   {{{1
    ------------------------------------------------------------------------

    filelists.c = {
      'autoload/mmtemplates/',
      ...

**Comment by snakeleon** [comment]
Okey~ thanks for telling me .
