### ISSUE TITLE
Perl-support SEGV on syntax check

### ISSUE THREAD

**Issue by horrendo** [WolfgangMehner/vim-plugins#35]
Vim version 7.4 on rhel6
perl-support version 5.4
perl version 5.16.3

[stbaldwin@audev04 framework][1]☢ head -1 bin/rjx.plx
#!/usr/bin/env perl
[stbaldwin@audev04 framework][1]☢ gvim bin/rjx.plx
[stbaldwin@audev04 framework][1]☢ Vim: Caught deadly signal SEGV
Vim: Finished.
[stbaldwin@audev04 framework][1]☢ tail -2 ~/.vimrc
filetype plugin on
let g:Perl_DirectRun  = 'yes'

The SEGV occurs when I choose Perl, Run, update. check syntax

running perltidy seems to work ok.

I'm not sure where to start looking for the problem.

Thanks,

Steve

**Comment by WolfgangMehner** [comment]
The perl syntax checker segfaults and Vim continues running? Or Vim segfaults itself?

**Comment by horrendo** [comment]
Vim reports catching signal SEGV and then terminates.

**Comment by WolfgangMehner** [comment]
Which patchlevel do you have? (Run `:version` on the Vim command line.)

**Comment by horrendo** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 11:14:07)
Included patches: 1-207, 209-629
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +conceal         +farsi           +libcall         +mouse_netterm   +profile         +syntax          +visualextra
+arabic          +cryptv          +file_in_path    +linebreak       +mouse_sgr       +python/dyn      +tag_binary      +viminfo
+autocmd         +cscope          +find_in_path    +lispindent      -mouse_sysmouse  -python3         +tag_old_static  +vreplace
-balloon_eval    +cursorbind      +float           +listcmds        +mouse_urxvt     +quickfix        -tag_any_white   +wildignore
-browse          +cursorshape     +folding         +localmap        +mouse_xterm     +reltime         -tcl             +wildmenu
++builtin_terms  +dialog_con      -footer          -lua             +multi_byte      +rightleft       +terminfo        +windows
+byte_offset     +diff            +fork()          +menu            +multi_lang      -ruby            +termresponse    +writebackup
+cindent         +digraphs        +gettext         +mksession       -mzscheme        +scrollbind      +textobjects     -X11
-clientserver    -dnd             -hangul_input    +modify_fname    +netbeans_intg   +signs           +title           -xfontset
-clipboard       -ebcdic          +iconv           +mouse           +path_extra      +smartindent     -toolbar         -xim
+cmdline_compl   +emacs_tags      +insert_expand   -mouseshape      +perl            -sniff           +user_commands   -xsmp
+cmdline_hist    +eval            +jumplist        +mouse_dec       +persistent_undo +startuptime     +vertsplit       -xterm_clipboard
+cmdline_info    +ex_extra        +keymap          +mouse_gpm       +postscript      +statusline      +virtualedit     -xterm_save
+comments        +extra_search    +langmap         -mouse_jsbterm   +printer         -sun_workshop    +visual          -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune
=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl  -lselinux  -ltinfo -lacl
 -lattr -lgpm   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt
-lutil -lpthread -lc

**Comment by WolfgangMehner** [comment]
The code in question only runs VimScript commands and calls an external program for the syntax checking. Non of this should cause  Vim to SEGV, unless there is some problem with Vim. Can you run a Perl script, using the plug-in? Do you have access to other versions of Vim you could try, or you use the one from the package manager?

**Comment by horrendo** [comment]
Thanks Wolfgang.  I have tried with Vim on my laptop (Mac) and everything works just fine so I guess it is a problem with the version of Vim on the server.  I'll try and get our tech support guys to install a newer version.

**Comment by WolfgangMehner** [comment]
You're welcome. Let me know if there are still problems.
