### ISSUE TITLE
template error message

### ISSUE THREAD

**Issue by GianniGi** [WolfgangMehner/vim-plugins#37]
Please help me to disable one and for all this message.
I've compiled the data required, but this continues to popup.
I need this to go away forever. I don't need any header.
thanks

vim 8.0124
windows 81

The personal details (name, mail, ...) are not set in the template library.
They are used to generate comments, ...
To set them, start the setup wizard using:
- use the menu entry "Vim -> Snippets -> template setup wizard"
- use the map "\ntw" inside a Vim buffer

**Comment by a-eid** [comment]
+1

**Comment by WolfgangMehner** [comment]
I already changed the behavior for C, Perl, Vim, Lua, and LaTeX.

I will also push the changes to the individual repositories.

**Comment by WolfgangMehner** [comment]
Also changed in AWK and Bash.

**Comment by WolfgangMehner** [comment]
Uploaded to the following individual repos:

```
WolfgangMehner/awk-support   yes
WolfgangMehner/bash-support
WolfgangMehner/c-support
WolfgangMehner/latex-support yes
WolfgangMehner/lua-support   yes
WolfgangMehner/perl-support
WolfgangMehner/vim-support   yes
```
