### ISSUE TITLE
Bash support: broken highlighting on ${var/pat/}

### ISSUE THREAD

**Issue by jones77** [WolfgangMehner/vim-plugins#41]
In the following file:

    #!/usr/bin/env bash
    echo "${x/ --/}" && echo hello

bash syntax highlighting is broken after that last `/`

**Comment by WolfgangMehner** [comment]
Please have a look at the file `$VIMRUNTIME/syntax/sh.vim`. It lists the maintainer of the syntax highlighting for shell, which is not part of our project:

    " Vim syntax file
    " Language:		shell (sh) Korn shell (ksh) bash (sh)
    " Maintainer:		Charles E. Campbell  <NdrOchipS@PcampbellAfamily.Mbiz>
    " Previous Maintainer:	Lennart Schultz <Lennart.Schultz@ecmwf.int>
    " Last Change:		Sep 22, 2016
    " Version:		165
    " URL:		http://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH
    " For options and settings, please use:      :help ft-sh-syntax
    " This file includes many ideas from Eric Brunet (eric.brunet@ens.fr)
    
    ...
