### ISSUE TITLE
C-Support: header and implementation comment interchanged

### ISSUE THREAD

**Issue by fidelski** [WolfgangMehner/vim-plugins#43]
When I create a new `cpp` file I would expect the implementation comment from `cpp.comments.template` to be inserted at the top. On the other hand when I create a `hpp` file I would expect the header comment to appear the top of the file - since my last update (unfortunately I don't remember when I did it or from what version to what version I moved) the wrong comments get inserted - the header comments appear in the implementation file and the implementation comments appear in the header file. Before this update everything worked (like a charm - like everything else still does).
I can workaround the issue by placing the content of the header file beneath:
```vim
== Comments.file description impl == map:cfdi, shortcut:c, start, noindent ==
```
and the comments for the implementation file beneath:
```vim
== Comments.file description header == map:cfdh, shortcut:h, start, noindent ==
```

At this opportunity I would like to express my gratitude for this outstanding plugin that has for multiple years boosted my productivity in C/C++ programming to a great extent. Thank you very much!

**Comment by WolfgangMehner** [comment]
Little switcheroo. Should work now.

Thank you for your kind words.
