### ISSUE TITLE
c-support: Modified class template ignores filename

### ISSUE THREAD

**Issue by AndreasAZiegler** [WolfgangMehner/vim-plugins#46]
I adjusted the c++ class template to the following

```
== C++.class == map:+c, shortcut:c ==
class |CLASSNAME| {
 public:
  |CLASSNAME| ();

 protected:

 private:

}; /* -----  end of class |CLASSNAME|  ----- */
```

When I now press ```\+c``` the template is inserted without asking for the ```CLASSNAME``` and the ```CLASSNAME``` results in an empty string.

**Comment by WolfgangMehner** [comment]
Add a `?` to the first macro:

```
== C++.class == map:+c, shortcut:c ==
class |?CLASSNAME| {
 public:
  |CLASSNAME| ();

 protected:

 private:

}; /* -----  end of class |CLASSNAME|  ----- */
```

Compare the [template help on macros](https://wolfgangmehner.github.io/vim-plugins/doc/templatesupport.html#template-support-templ-macro).

**Comment by AndreasAZiegler** [comment]
Thanks, that indeed worked.
