### ISSUE TITLE
c-support: Spacing in template is ignored

### ISSUE THREAD

**Issue by AndreasAZiegler** [WolfgangMehner/vim-plugins#47]
I have the following c++ class template

```
== C++.class == map:+c, shortcut:c ==
class |?CLASSNAME:c| {
 public:
  |CLASSNAME| ();

 protected:

 private:

}; /* -----  end of class |CLASSNAME|  ----- */
```

When I now press ```\+c``` the template with the entered class name is inserted but the spacing is not as in the template. See an example below.

```
class Test {
  public:
    Test();

     

  protected:

  private:

}; /* -----  end of class Test  ----- */
```
The inserted template has two blanks before public (instead of one blank) and four blanks before the constructor (instead of two blanks). Somehow it feels like the spacing is dictated by the "global" vim indent settings but I am not sure.

**Comment by WolfgangMehner** [comment]
You can add the [noindent option](https://wolfgangmehner.github.io/vim-plugins/doc/templatesupport.html#template-support-noindent) to the template:
```
== C++.class == noindent, map:+c, shortcut:c ==
class |?CLASSNAME:c| {
 public:
 ...
```

If you actually want all indentation to be only one space, use `set shiftwidth=1` in your C/C++ filetype plug-in.

If you want class definitions and functions treated differently by your automatic indentation, you could search for a non-default indent expression (`:help 'indentexpr'`). But I do not know whether plug-ins like this exist.

**Comment by AndreasAZiegler** [comment]
Thanks. This answered my question and solved my problem. Thanks for the support.
